language: python
os: linux

python:
    - "3.6"

services:
    - docker

branches:
    only:
        - develop
        - master

script:
    - echo $DOCKER_PASS | docker login azolotukhin.jfrog.io -u $DOCKER_USER --password-stdin
    - docker build -t azolotukhin.jfrog.io/docker/my-docker-image:latest .

after_success:
    - docker push azolotukhin.jfrog.io/docker/my-docker-image:latest